services:
  mariadb:
    container_name: mariadb
    init: true
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - .env
    build: requirements/mariadb
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    image: mariadb
  nginx:
    container_name: nginx
    init: true
    restart: on-failure
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    env_file:
      - .env
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html 
    networks:
      - inception
    depends_on:
      - wordpress
    image: nginx
  wordpress:
    container_name: wordpress
    init: true
    restart: no
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - WORDPRESS_EMAIL=${WORDPRESS_EMAIL}
    build: requirements/wordpress
    expose:
      - "9000"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    image: wordpress 

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/inception_data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/inception_data/wordpress

networks:
  inception:
    name: inception
    driver: bridge
